version: "3.8"

x-service-volumes: &service-volumes
  - ./:/esociety/:rw,cached

services: 
  website:
    image: esociety:test
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    ports:
      - "8000:8000" 

